/**
 * Generates code-derived reference pages for the docs site.
 * Inputs:  prisma/schema.prisma, src/app/api/**\/route.ts, .env.example
 * Outputs: src/content/docs/reference/{schema,api,env}.mdx
 * Run on every docs build (CI + local) — never commits to the repo.
 */
import { readFileSync, writeFileSync, readdirSync, statSync } from "node:fs";
import { join, relative, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const siteRoot = dirname(dirname(fileURLToPath(import.meta.url))); // docs-site/
const repoRoot = dirname(siteRoot);
const OUT = join(siteRoot, "src", "content", "docs", "reference");
const repo = (p) => join(repoRoot, p);

const BANNER = (src, path) =>
  `> [!NOTE]\n> AUTOGENERATED by docs-site/scripts/gen.mjs from \`${path}\` — DO NOT EDIT.\n> Changes belong in the source file; regenerated on every build.\n\n`;

function collectRouteFiles(dir) {
  const out = [];
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) out.push(...collectRouteFiles(p));
    else if (name === "route.ts") out.push(p);
  }
  return out;
}

function writePage(name, title, md) {
  writeFileSync(join(OUT, `${name}.mdx`), `---\ntitle: ${title}\n---\n\n` + md);
}

// ---------------------------------------------------------------- schema.mdx
function genSchema() {
  const src = readFileSync(repo("prisma/schema.prisma"), "utf8");
  const models = [];
  const enums = [];
  let current = null;
  let inEnum = false;

  for (const line of src.split("\n")) {
    const t = line.trim();
    const modelMatch = t.match(/^model (\w+)/);
    const enumMatch = t.match(/^enum (\w+)/);
    if (modelMatch) {
      current = { name: modelMatch[1], fields: [] };
      models.push(current);
      inEnum = false;
      continue;
    }
    if (enumMatch) {
      current = { name: enumMatch[1], values: [] };
      enums.push(current);
      inEnum = true;
      continue;
    }
    if (current && (t === "}" || t === "")) {
      if (t === "}") current = null;
      continue;
    }
    if (!current || t.startsWith("//") || t.startsWith("@@") || t.startsWith("///")) continue;
    if (inEnum) {
      if (!/^\w+$/.test(t)) continue;
      current.values.push(t);
    } else {
      const m = t.match(/^(\w+)\s+(.+?)(\s+\/\/.*)?$/) ?? t.match(/^(\w+)/);
      if (!m) continue;
      const name = m[1];
      const rest = (m[2] ?? "").trim();
      const attrs = rest.match(/@[^ ]+.*/)?.[0] ?? "";
      const type = rest.replace(/@.*/, "").trim();
      current.fields.push(
        `| \`${name}\` | \`${type}\`${attrs ? " · " + attrs.replace(/^\|/, "").trim() : ""} |`
      );
    }
  }

  let md = "";
  for (const model of models) {
    md += `### ${model.name}\n\n| Feld | Typ |\n| ---- | --- |\n`;
    md += model.fields.map((f) => f.replace(/\s{2,}/g, " ")).join("\n");
    md += "\n\n";
  }
  if (enums.length) {
    md += "### Enums\n\n";
    for (const e of enums) {
      md += `- **${e.name}**: ${e.values.map((v) => `\`${v}\``).join(" · ")}\n`;
    }
  }
  writePage("schema", "Datenmodell (Prisma Schema)", BANNER(src, "prisma/schema.prisma") + md);
}

// ------------------------------------------------------------------- api.mdx
function genApi() {
  const routes = collectRouteFiles(repo("src/app/api"))
    .sort()
    .map((file) => {
      const src = readFileSync(file, "utf8");
      const rel = relative(repoRoot, file).replace(/\\/g, "/");
      const routePath =
        "/" +
        relative(repo("src/app/api"), file)
          .replace(/\\/g, "/")
          .replace(/\/route\.ts$/, "")
          .replace(/\/\([\w.]+\)\//g, "/")
          .replace(/\/+/g, "/")
          .replace(/\[(\.\.\.)?(\w+)\]/g, ":$2");
      const methods = [];
      for (const m of ["GET", "POST", "PUT", "PATCH", "DELETE"]) {
        if (new RegExp(`export async function ${m}\\b`).test(src)) {
          let note = "";
          if (/requireAdmin/.test(src)) note = " — admin only";
          else if (/requireUser/.test(src)) note = " — auth required";
          else if (/kiosk/.test(rel)) note = " — kiosk (host-gated, unauthenticated)";
          methods.push(`- \`${m}\`${note}`);
        }
      }
      return { routePath, rel, methods };
    })
    .filter((r) => r.methods.length > 0);

  let md = "";
  for (const r of routes) {
    md += `### \`${r.routePath}\`\n\n`;
    md += r.methods.join("\n");
    md += `\n\n> Quelle: [\`${r.rel}\`](https://github.com/2TAP2B/chronify/blob/main/${r.rel})\n\n`;
  }
  writePage(
    "api",
    "API-Endpunkte",
    BANNER("", "src/app/api/**/route.ts") + `Insgesamt ${routes.length} Route-Dateien.\n\n` + md
  );
}

// -------------------------------------------------------------------- env.mdx
function genEnv() {
  const src = readFileSync(repo(".env.example"), "utf8");
  const lines = src.split("\n");
  const blocks = [];
  let currentComment = [];
  let currentVars = [];

  const flush = () => {
    if (!currentVars.length) return;
    blocks.push({ comment: currentComment, vars: currentVars });
    currentComment = [];
    currentVars = [];
  };

  for (const line of lines) {
    const t = line.trim();
    if (t.startsWith("#")) {
      currentComment.push(t.replace(/^#\s?/, ""));
      continue;
    }
    if (t.startsWith("#")) continue;
    if (t === "") {
      flush();
      continue;
    }
    const m = t.match(/^([A-Z0-9_]+)="(.*)"/);
    if (m) {
      currentVars.push({ key: m[1], value: m[2] });
    }
  }
  flush();

  let md = "| Variable | Example-Wert | Beschreibung |\n| --- | --- | --- |\n";
  for (const b of blocks) {
    if (!b.comment.length || !b.vars.length) continue;
    const desc = b.comment.filter(
      (c) => !/^(for|Generate with|NOTE|Create|---|→)/i.test(c) && !c.startsWith("=")
    );
    const descText = b.comment.length ? escape(desc[0] ?? "") : "";
    for (let i = 0; i < b.vars.length; i++) {
      const v = b.vars[i];
      const shown = v.value === "" ? "*leer*" : `\`${escape(v.value)}\``;
      md += `| \`${v.key}\` | ${shown} | ${i === 0 ? descText : ""} |\n`;
    }
  }
  writePage("env", "Environment-Variablen", BANNER(src, ".env.example") + md);
}

function escape(s) {
  return s.replace(/\|/g, "\\|").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

// --------------------------------------------------------------------- main
genSchema();
genApi();
genEnv();
console.log("generated: schema.mdx, api.mdx, env.mdx");
